repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
  - repo: local
    hooks:
      - id: sort-manifest
        name: Sort manifest.json
        entry: bash -c 'jq --indent 2 " {domain, name} + (del(.domain, .name) | to_entries | sort_by(.key) | from_entries) " custom_components/nrg_gyms/manifest.json > custom_components/nrg_gyms/manifest.json.tmp && mv custom_components/nrg_gyms/manifest.json.tmp custom_components/nrg_gyms/manifest.json'
        language: system
        files: manifest.json
